name: Claude Code ScrollFX

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]

jobs:
  claude:
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.title, '[Claude]')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@main
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: agent
          max_turns: 30
          model: claude-3-5-sonnet-20241022
          custom_instructions: |
            You are working on ScrollFX, which combines Scroll window manager with SceneFX cosmetic features.
            
            IMPORTANT: Always check CLAUDE.md for project context and guidelines.
            
            Key points:
            1. Scroll uses sway_scene_* instead of wlr_scene_*
            2. Reference code is in /references/ subdirectories (READ-ONLY)
            3. Always create report-{taskname}.md documenting your work
            4. Use investigation-*.md files for understanding integration patterns
            
            When analyzing code, be precise about which files and directories to examine.
          allowed_tools: "str_replace_editor,create_file,edit_file,view_file,list_files,bash,git"
